DASHBOARD = {
    "summary": [
        {
            "label": "Funds Monitored",
            "value": "142",
            "change": "8.2%",
            "trend": "up",
            "icon": "activity",
        },
        {
            "label": "Total AUM Tracked",
            "value": "$15.0B",
            "change": "12.5%",
            "trend": "up",
            "icon": "dollar",
        },
        {
            "label": "Avg. YTD Return",
            "value": "+12.5%",
            "change": "3.1%",
            "trend": "up",
            "icon": "trending",
        },
        {
            "label": "Active Alerts",
            "value": "24",
            "change": "15%",
            "trend": "down",
            "icon": "alert",
        },
    ],
    "performance": [
        {"month": "Jul", "portfolio": 2.0, "benchmark": 1.0},
        {"month": "Aug", "portfolio": 3.0, "benchmark": 2.0},
        {"month": "Sep", "portfolio": 2.0, "benchmark": 2.5},
        {"month": "Oct", "portfolio": 4.0, "benchmark": 3.0},
        {"month": "Nov", "portfolio": 4.0, "benchmark": 4.0},
        {"month": "Dec", "portfolio": 8.0, "benchmark": 5.0},
        {"month": "Jan", "portfolio": 9.0, "benchmark": 5.5},
        {"month": "Feb", "portfolio": 7.0, "benchmark": 6.0},
        {"month": "Mar", "portfolio": 9.0, "benchmark": 6.5},
        {"month": "Apr", "portfolio": 10.0, "benchmark": 7.0},
        {"month": "May", "portfolio": 13.0, "benchmark": 7.5},
        {"month": "Jun", "portfolio": 13.0, "benchmark": 8.0},
    ],
    "allocation": [
        {"name": "Hedge Funds", "value": 32, "color": "#2563eb"},
        {"name": "Private Equity", "value": 25, "color": "#60a5fa"},
        {"name": "Venture Capital", "value": 18, "color": "#22c55e"},
        {"name": "Real Assets", "value": 12, "color": "#f97316"},
        {"name": "Fixed Income", "value": 8, "color": "#ef4444"},
        {"name": "Public Equity", "value": 5, "color": "#a855f7"},
    ],
    "alerts": [
        {
            "id": "1",
            "title": "Tiger Global +25% YTD",
            "description": "Outperforming benchmark by 17.3pp",
            "time": "2h ago",
            "type": "performance",
        },
        {
            "id": "2",
            "title": "Bridgewater drawdown alert",
            "description": "Pure Alpha fund down -3.1% YTD",
            "time": "4h ago",
            "type": "warning",
        },
        {
            "id": "3",
            "title": "PM departure at Citadel",
            "description": "Senior PM Alex Chen leaving",
            "time": "6h ago",
            "type": "person",
        },
        {
            "id": "4",
            "title": "Baupost ADV amendment",
            "description": "Updated Form ADV filed with SEC",
            "time": "1d ago",
            "type": "document",
        },
        {
            "id": "5",
            "title": "Renaissance +32.1%",
            "description": "Top performer in universe",
            "time": "1d ago",
            "type": "performance",
        },
    ],
}
